version: '3.9'

services:
  database:
    image: postgres:14.1-alpine
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
